// <auto-generated />
using System;
using Lam3a.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lam3a.Migrations
{
    [DbContext(typeof(DataContextEf))]
    [Migration("20251127091226_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lam3a.Data.Entities.FavoriteProvider", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("ClientId", "ServiceProviderId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("FavoriteProviders");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TokenId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.SeedStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SeedStatus");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Dry Clean"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Exterior Wash"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Interior Wash"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Name = "Full Wash"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Name = "Wax & Polish"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Name = "Interior Detailing"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Name = "Exterior Detailing"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Name = "Headlight Restoration"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Name = "Leather Seat Conditioning"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            Name = "Odor Removal / Ozone Treatment"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000b"),
                            Name = "Ceramic Coating"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000c"),
                            Name = "Paint Protection Film (PPF)"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000d"),
                            Name = "Engine Bay Cleaning"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000e"),
                            Name = "Underbody Wash"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000f"),
                            Name = "Tire & Rim Polishing"
                        });
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehiclePlateNumber")
                        .IsRequired()
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("VehiclePlateNumber");

                    b.ToTable("ServiceRequests", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("UserAccountStatus")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Vehicle", b =>
                {
                    b.Property<string>("PlateNumber")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("CarType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.HasKey("PlateNumber");

                    b.HasIndex("BrandId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ModelId");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.VehicleBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VehicleBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 9,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lexus"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Land Rover"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Jaguar"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 19,
                            Name = "GMC"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Cadillac"
                        });
                });

            modelBuilder.Entity("Lam3a.Data.Entities.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "Camry"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "Corolla"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Name = "Land Cruiser"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            Name = "Crown"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Name = "Hilux"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            Name = "RAV4"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            Name = "Highlander"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            Name = "Civic"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            Name = "Accord"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            Name = "CR-V"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            Name = "Pilot"
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 2,
                            Name = "City"
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            Name = "Sunny"
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            Name = "Sentra"
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 3,
                            Name = "Altima"
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 3,
                            Name = "Patrol"
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 3,
                            Name = "X-Trail"
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 4,
                            Name = "Accent"
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 4,
                            Name = "Elantra"
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 4,
                            Name = "Sonata"
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 4,
                            Name = "Tucson"
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 4,
                            Name = "Santa Fe"
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 5,
                            Name = "Rio"
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 5,
                            Name = "Cerato"
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 5,
                            Name = "K5"
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 5,
                            Name = "Sportage"
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 5,
                            Name = "Sorento"
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 6,
                            Name = "Taurus"
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 6,
                            Name = "Mustang"
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 6,
                            Name = "Explorer"
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 6,
                            Name = "F-150"
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 6,
                            Name = "Expedition"
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 7,
                            Name = "Spark"
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 7,
                            Name = "Malibu"
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 7,
                            Name = "Camaro"
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 7,
                            Name = "Tahoe"
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 7,
                            Name = "Silverado"
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 8,
                            Name = "C-Class"
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 8,
                            Name = "E-Class"
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 8,
                            Name = "S-Class"
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 8,
                            Name = "G-Class"
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 9,
                            Name = "3 Series"
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 9,
                            Name = "5 Series"
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 9,
                            Name = "7 Series"
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 9,
                            Name = "X5"
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 10,
                            Name = "IS"
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 10,
                            Name = "ES"
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 10,
                            Name = "LS"
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 10,
                            Name = "LX"
                        },
                        new
                        {
                            Id = 50,
                            BrandId = 10,
                            Name = "RX"
                        },
                        new
                        {
                            Id = 51,
                            BrandId = 11,
                            Name = "A3"
                        },
                        new
                        {
                            Id = 52,
                            BrandId = 11,
                            Name = "A4"
                        },
                        new
                        {
                            Id = 53,
                            BrandId = 11,
                            Name = "A6"
                        },
                        new
                        {
                            Id = 54,
                            BrandId = 11,
                            Name = "Q5"
                        },
                        new
                        {
                            Id = 55,
                            BrandId = 11,
                            Name = "Q7"
                        },
                        new
                        {
                            Id = 56,
                            BrandId = 12,
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 57,
                            BrandId = 12,
                            Name = "Jetta"
                        },
                        new
                        {
                            Id = 58,
                            BrandId = 12,
                            Name = "Passat"
                        },
                        new
                        {
                            Id = 59,
                            BrandId = 12,
                            Name = "Tiguan"
                        },
                        new
                        {
                            Id = 60,
                            BrandId = 12,
                            Name = "Touareg"
                        },
                        new
                        {
                            Id = 61,
                            BrandId = 13,
                            Name = "911"
                        },
                        new
                        {
                            Id = 62,
                            BrandId = 13,
                            Name = "Cayenne"
                        },
                        new
                        {
                            Id = 63,
                            BrandId = 13,
                            Name = "Macan"
                        },
                        new
                        {
                            Id = 64,
                            BrandId = 13,
                            Name = "Panamera"
                        },
                        new
                        {
                            Id = 65,
                            BrandId = 13,
                            Name = "Taycan"
                        },
                        new
                        {
                            Id = 66,
                            BrandId = 14,
                            Name = "Range Rover"
                        },
                        new
                        {
                            Id = 67,
                            BrandId = 14,
                            Name = "Defender"
                        },
                        new
                        {
                            Id = 68,
                            BrandId = 14,
                            Name = "Discovery"
                        },
                        new
                        {
                            Id = 69,
                            BrandId = 14,
                            Name = "Evoque"
                        },
                        new
                        {
                            Id = 70,
                            BrandId = 14,
                            Name = "Velar"
                        },
                        new
                        {
                            Id = 71,
                            BrandId = 15,
                            Name = "XE"
                        },
                        new
                        {
                            Id = 72,
                            BrandId = 15,
                            Name = "XF"
                        },
                        new
                        {
                            Id = 73,
                            BrandId = 15,
                            Name = "F-Pace"
                        },
                        new
                        {
                            Id = 74,
                            BrandId = 15,
                            Name = "E-Pace"
                        },
                        new
                        {
                            Id = 75,
                            BrandId = 15,
                            Name = "F-Type"
                        },
                        new
                        {
                            Id = 76,
                            BrandId = 16,
                            Name = "Mazda3"
                        },
                        new
                        {
                            Id = 77,
                            BrandId = 16,
                            Name = "Mazda6"
                        },
                        new
                        {
                            Id = 78,
                            BrandId = 16,
                            Name = "CX-5"
                        },
                        new
                        {
                            Id = 79,
                            BrandId = 16,
                            Name = "CX-9"
                        },
                        new
                        {
                            Id = 80,
                            BrandId = 16,
                            Name = "CX-30"
                        },
                        new
                        {
                            Id = 81,
                            BrandId = 17,
                            Name = "Impreza"
                        },
                        new
                        {
                            Id = 82,
                            BrandId = 17,
                            Name = "Legacy"
                        },
                        new
                        {
                            Id = 83,
                            BrandId = 17,
                            Name = "Outback"
                        },
                        new
                        {
                            Id = 84,
                            BrandId = 17,
                            Name = "Forester"
                        },
                        new
                        {
                            Id = 85,
                            BrandId = 17,
                            Name = "Crosstrek"
                        },
                        new
                        {
                            Id = 86,
                            BrandId = 18,
                            Name = "Lancer"
                        },
                        new
                        {
                            Id = 87,
                            BrandId = 18,
                            Name = "Pajero"
                        },
                        new
                        {
                            Id = 88,
                            BrandId = 18,
                            Name = "Outlander"
                        },
                        new
                        {
                            Id = 89,
                            BrandId = 18,
                            Name = "ASX"
                        },
                        new
                        {
                            Id = 90,
                            BrandId = 18,
                            Name = "Eclipse Cross"
                        },
                        new
                        {
                            Id = 91,
                            BrandId = 19,
                            Name = "Sierra"
                        },
                        new
                        {
                            Id = 92,
                            BrandId = 19,
                            Name = "Yukon"
                        },
                        new
                        {
                            Id = 93,
                            BrandId = 19,
                            Name = "Terrain"
                        },
                        new
                        {
                            Id = 94,
                            BrandId = 19,
                            Name = "Acadia"
                        },
                        new
                        {
                            Id = 95,
                            BrandId = 19,
                            Name = "Canyon"
                        },
                        new
                        {
                            Id = 96,
                            BrandId = 20,
                            Name = "Escalade"
                        },
                        new
                        {
                            Id = 97,
                            BrandId = 20,
                            Name = "CT5"
                        },
                        new
                        {
                            Id = 98,
                            BrandId = 20,
                            Name = "XT5"
                        },
                        new
                        {
                            Id = 99,
                            BrandId = 20,
                            Name = "XT6"
                        },
                        new
                        {
                            Id = 100,
                            BrandId = 20,
                            Name = "CT4"
                        });
                });

            modelBuilder.Entity("Lam3a.Data.ValueObjects.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.ValueObjects.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.ValueObjects.TimeSlot", b =>
                {
                    b.Property<Guid>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("interval");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("interval");

                    b.HasKey("TimeSlotId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("TimeSlots", (string)null);
                });

            modelBuilder.Entity("ProviderService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ProviderServices", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Client", b =>
                {
                    b.HasBaseType("Lam3a.Data.Entities.User");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceProvider", b =>
                {
                    b.HasBaseType("Lam3a.Data.Entities.User");

                    b.Property<bool>("Availability")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.ToTable("ServiceProviders", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.FavoriteProvider", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.Client", "Client")
                        .WithMany("FavoriteProviders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("FavoritedByClients")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Notification", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceRequest", b =>
                {
                    b.HasOne("Lam3a.Data.ValueObjects.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProviderService", "Service")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.Entities.ServiceProvider", "provider")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.ValueObjects.TimeSlot", "TimeSlot")
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehiclePlateNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Service");

                    b.Navigation("TimeSlot");

                    b.Navigation("Vehicle");

                    b.Navigation("provider");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Vehicle", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.VehicleBrand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.Entities.Client", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.Entities.VehicleModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Client");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.VehicleModel", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.VehicleBrand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Lam3a.Data.ValueObjects.Address", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("Lam3a.Data.ValueObjects.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lam3a.Data.ValueObjects.Coordinates", "MapCoordinates", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("numeric");

                            b1.HasKey("AddressId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.Navigation("MapCoordinates")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lam3a.Data.ValueObjects.Schedule", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("Schedules")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Lam3a.Data.ValueObjects.TimeSlot", b =>
                {
                    b.HasOne("Lam3a.Data.ValueObjects.Schedule", "Schedule")
                        .WithMany("TimeSlots")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ProviderService", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("Services")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Client", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Lam3a.Data.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceProvider", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Lam3a.Data.Entities.ServiceProvider", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.User", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.VehicleBrand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Lam3a.Data.ValueObjects.Schedule", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("ProviderService", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Client", b =>
                {
                    b.Navigation("FavoriteProviders");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceProvider", b =>
                {
                    b.Navigation("FavoritedByClients");

                    b.Navigation("Schedules");

                    b.Navigation("ServiceRequests");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
