// <auto-generated />
using System;
using Lam3a.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lam3a.Migrations
{
    [DbContext(typeof(DataContextEf))]
    [Migration("20251102145640_AddNewEntities")]
    partial class AddNewEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lam3a.Data.Entities.FavoriteProvider", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("ClientId", "ServiceProviderId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("FavoriteProviders");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Notification", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ProviderService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstimatedTime")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ProviderServices", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TokenId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("ServiceCategories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CategoryName = "Dry Clean"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CategoryName = "Exterior Wash"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CategoryName = "Interior Wash"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000004"),
                            CategoryName = "Full Wash"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000005"),
                            CategoryName = "Wax & Polish"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000006"),
                            CategoryName = "Interior Detailing"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000007"),
                            CategoryName = "Exterior Detailing"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000008"),
                            CategoryName = "Headlight Restoration"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-000000000009"),
                            CategoryName = "Leather Seat Conditioning"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-00000000000a"),
                            CategoryName = "Odor Removal / Ozone Treatment"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-00000000000b"),
                            CategoryName = "Ceramic Coating"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-00000000000c"),
                            CategoryName = "Paint Protection Film (PPF)"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-00000000000d"),
                            CategoryName = "Engine Bay Cleaning"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-00000000000e"),
                            CategoryName = "Underbody Wash"
                        },
                        new
                        {
                            CategoryId = new Guid("10000000-0000-0000-0000-00000000000f"),
                            CategoryName = "Tire & Rim Polishing"
                        });
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceRequests", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceTag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagId");

                    b.ToTable("ServiceTags", (string)null);

                    b.HasData(
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TagName = "Premium"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111112"),
                            TagName = "Eco-Friendly"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111113"),
                            TagName = "Affordable"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111114"),
                            TagName = "Fast Service"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111115"),
                            TagName = "Phone Support"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111116"),
                            TagName = "24/7 Availability"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111117"),
                            TagName = "Waterless"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111118"),
                            TagName = "Interior Specialist"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111119"),
                            TagName = "Exterior Specialist"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111120"),
                            TagName = "Luxury Cars"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111121"),
                            TagName = "Pickup & Drop-off"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111122"),
                            TagName = "Pet Hair Removal"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111123"),
                            TagName = "Family Friendly"
                        },
                        new
                        {
                            TagId = new Guid("11111111-1111-1111-1111-111111111124"),
                            TagName = "Contactless Payment"
                        });
                });

            modelBuilder.Entity("Lam3a.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("UserAccountStatus")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Vehicle", b =>
                {
                    b.Property<string>("PlateNumber")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.HasKey("PlateNumber");

                    b.HasIndex("BrandId");

                    b.HasIndex("ClientUserId");

                    b.HasIndex("ModelId");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.VehicleBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VehicleBrands");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.VehicleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("Lam3a.Data.ValueObjects.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.ValueObjects.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("ProviderServiceServiceTag", b =>
                {
                    b.Property<Guid>("ServiceTagsTagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("uuid");

                    b.HasKey("ServiceTagsTagId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ProviderServiceServiceTag");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Client", b =>
                {
                    b.HasBaseType("Lam3a.Data.Entities.User");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceProvider", b =>
                {
                    b.HasBaseType("Lam3a.Data.Entities.User");

                    b.Property<bool>("Availability")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.ToTable("ServiceProviders", (string)null);
                });

            modelBuilder.Entity("Lam3a.Data.Entities.FavoriteProvider", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.Client", "Client")
                        .WithMany("FavoriteProviders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("FavoritedByClients")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Notification", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ProviderService", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("Services")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceCategory");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceRequest", b =>
                {
                    b.HasOne("Lam3a.Data.ValueObjects.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.Entities.ProviderService", "ProviderService")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lam3a.Data.ValueObjects.TimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<Guid>("ServiceRequestId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("End")
                                .HasColumnType("interval");

                            b1.Property<TimeSpan>("Start")
                                .HasColumnType("interval");

                            b1.HasKey("ServiceRequestId");

                            b1.ToTable("ServiceRequests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId");
                        });

                    b.Navigation("Address");

                    b.Navigation("ProviderService");

                    b.Navigation("TimeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Vehicle", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.VehicleBrand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.Entities.Client", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientUserId");

                    b.HasOne("Lam3a.Data.Entities.VehicleModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.VehicleModel", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.VehicleBrand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Lam3a.Data.ValueObjects.Address", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("Lam3a.Data.ValueObjects.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lam3a.Data.ValueObjects.Coordinates", "MapCoordinates", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("numeric");

                            b1.HasKey("AddressId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.Navigation("MapCoordinates")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lam3a.Data.ValueObjects.Schedule", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.ServiceProvider", "ServiceProvider")
                        .WithMany("Schedules")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Lam3a.Data.ValueObjects.TimeRange", "TimeRange", b1 =>
                        {
                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("End")
                                .HasColumnType("interval");

                            b1.Property<TimeSpan>("Start")
                                .HasColumnType("interval");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedules");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.Navigation("ServiceProvider");

                    b.Navigation("TimeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("ProviderServiceServiceTag", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.ServiceTag", null)
                        .WithMany()
                        .HasForeignKey("ServiceTagsTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lam3a.Data.Entities.ProviderService", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Client", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Lam3a.Data.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceProvider", b =>
                {
                    b.HasOne("Lam3a.Data.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Lam3a.Data.Entities.ServiceProvider", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ProviderService", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.User", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.VehicleBrand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.Client", b =>
                {
                    b.Navigation("FavoriteProviders");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Lam3a.Data.Entities.ServiceProvider", b =>
                {
                    b.Navigation("FavoritedByClients");

                    b.Navigation("Schedules");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
